export const FETCH_USER = 'fetch_user'
export const FETCH_ALL_PETS = 'fetch_pets'
export const FETCH_FILTER = 'fetch_filter'

export const FETCH_SINGLE_PET = 'fetch_single_pet'
export const PET_MY_PET = 'pet_my_pet'
export const FEED_PET = 'feed_pet'
export const WALK_PET = 'walk_pet'
export const FETCH_USER_PET = 'fetch_user_pet'

export const ADD_TO_CART = 'ADD_TO_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const GET_NO_OF_USER_GOODIES = 'GET_NO_OF_USER_GOODIES'